services:
  pygege:
    build: .
    container_name: pygege-dev
    ports:
      - "8000:8000"
    volumes:
      - ./data:/app/data
      - .:/app
    env_file:
      - .env
    restart: unless-stopped